services:
  # Frontend React application
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"  # Maps port 5173 on the host to port 5173 in the container
    volumes:
      - ./frontend:/app  # Mounts the frontend directory for live reloading
      - /app/node_modules  # Anonymous volume to prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend  # Ensures backend is started before frontend

  # Backend Express application
  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "5001:5001"  # Maps port 5001 on the host to port 5001 in the container
      - "9229:9229" # Maps port 9229 on the host to port 9229 in the container for debugging
    volumes:
      - ./backend:/app  # Mounts the backend directory for live reloading
      - /app/node_modules  # Anonymous volume to prevent overwriting node_modules
    # environment:
    #   - POSTGRES_HOST
    #   - POSTGRES_PORT
    #   - POSTGRES_DB
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    #   - REDIS_URL
    #   - S3_ENDPOINT
    #   - S3_ACCESS_KEY
    #   - S3_SECRET_ACCESS_KEY
    #   - S3_BUCKET_NAME
    #   - API_PORT
    #   - OPENAI_API_KEY
    env_file:
      - .env
    command: sh -c "npm install && npm run dev:debug"
    depends_on:
      - postgres


  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER  # Sets the superuser name
      - POSTGRES_PASSWORD  # Sets the superuser password
      - POSTGRES_DB  # Sets the name of the default database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists database data
    ports:
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container

  # Redis + RedisStack database
  redis:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
      # - REDISINSIGHT_DEFAULT_USERNAME=default
      # - REDISINSIGHT_DEFAULT_PASSWORD=${REDIS_INSIGHT_PASSWORD}

  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio
    ports:
      - "${S3_PORT}:9000"
      - "${S3_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"

# Named volumes for persisting data
volumes:
  postgres_data:
  redis_data:
  minio_data:
