name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install
    - name: Run tests
      run: |
        cd frontend && npm test
        cd ../backend && npm test